### ISSUE TITLE
Intellij 2020.2 EAP gives error with RequiredArgsConstructor on Enum

### ISSUE THREAD

**Issue by BigBadE** [mplushnikov/lombok-intellij-plugin#814]
### Short description
_Provide a short description of the issue here. Do not include stacktraces in this sectrion_
@RequiredArgsConstructor gives error "Lombok needs a default constructor in the base class"
It appears to be because Lombok doesn't detect the class is an enum in Intellij 2020.2 EAP

### Expected behavior
_Is there a specific expected behavior?_
Lombok detects the class is an enum, and creates a proper constructor

### Version information

 * **IDEA Version:** Intellij 2020.2 EAP
 * **JDK Version:** 1.8.0_221
 * **OS Type & Version:** Windows 10, 10.0.18363
 * **Lombok Plugin Version:** 0.9.7.15
 * **Lombok Dependency Version:** Not Applicable

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Create an enum with a final field
 2. Add the @RequiredArgsConstructor annotation

Sample enum:
```
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum TestEnum {
    TEST("1");
    
    private final String test = "";
}
```
### Additional information
_Is there any additional information you can provide to help us understanding and solving the issue?_

Seems to only be in 2020.2 EAP, not reproducable in 2020.1
Maven still builds fine, so it's only a visual problem. 

Same issue as #172 which was fixed with this commit:
https://github.com/mplushnikov/lombok-intellij-plugin/commit/6fe8fba24d19d983bb20a6e6abcb4f61fc2ff8cb
so, it looks like PsiClass#isEnum always returns false, or enums are not a PsiAnonymousClass.
(That could be totally wrong, I do not know how the Intellij API works).

**Comment by mplushnikov** [comment]
@BigBadE Please update your lombok plugin to a new version. I released today a new one build for 2020.2 EAP. 
Your example contains an error: you have already an default initializer for field 'test'. Remove it and @RequiredArgsConstructor starts working.

**Comment by austinarbor** [comment]
@mplushnikov My 2020.2 EAP install is not able to find the updated plugin. Has it been published?

> 6/1/20
8:36 PM	Plugin Error: Plugin "Lombok" is incompatible (until build 201.SNAPSHOT < IU-202.4357.23).

<img width="373" alt="Screen Shot 2020-06-01 at 8 37 05 PM" src="https://user-images.githubusercontent.com/11469880/83467358-b1bfed00-a447-11ea-9821-8eede7a14e8b.png">

**Comment by BigBadE** [comment]
That was a mistake on my part, the issue persists even if no value is given for the String.

The issue was fixed in .30-EAP though, thanks!

**Comment by mplushnikov** [comment]
@austinarbor Yes, it's here https://plugins.jetbrains.com/plugin/6317-lombok/update/87712 
(With compatibility range 202.4357—202.*)

**Comment by austinarbor** [comment]
Thanks, installation manually worked. Not sure why it wasn't appearing in check for updates
